export * from './Navbar';
export * from './Inicio';
export * from './About';
export * from './Skill';
export * from './Icon';
export * from './Projects';
export * from './Cards';
export * from './Contact';
export * from './Footer';